server {
    listen 80;

    server_name localhost;

    # all the request to "/static" will be redirected to /usr/share/nginx/html/static
    location /static {
        root /usr/share/nginx/html ;
    }

    # other ones will be redirected to backend service(FASTapi service)
    location / {
        proxy_pass http://backend:8000;
    }
}